### ISSUE TITLE
Rocks/Shortcuts clicks too fast

### ISSUE THREAD

**Issue by finger1589** [PTYB/OpenAbyss#13]
When u enter abyss sometimes bot clicks pretty fast and it makes sometimes.ur caracter don't move cause it's still loading and takes up to 5 secs to reclick on rock/shortcut and makes u take alot of Damage so if u make the bot wait 1-2 secs since ineter the abyss for click rock/shortcut could make fix this.

**Comment by PTYB** [comment]
Should have been resolved
